spring:
  application:
    name: order-service
  cloud:
    #turn off override command line feature
    config:
      override-none: true
    
server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#ribbon:
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
